development:
  adapter: postgresql
  encoding: unicode
  database: fittastic_development
  pool: 5
  host: localhost
  username:
  password:
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: fittastic_test
  pool: 5
  host: localhost
  username:
  password:
  template: template0
