development:
  adapter: postgresql
  encoding: utf8
  database: fittastic_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: fittastic_test
  pool: 5
  host: localhost

production: '<%= ENV['HEROKU_POSTGRESQL_AQUA_URL'] %>'
